# Sample webserv configuration file for testing with the 42 tester
# Setup the configuration file as follow:
#
# - / must answer to GET request ONLY
#
# - Any file with .bla as extension must answer to
#   POST request by calling the cgi_test executable
#
# - /post_body must answer anything to POST request with
#   a maxBody of 100
#
# - /directory/ must answer to GET request and the root of it
#   would be the repository YoupiBanane and if no file are requested,
#   it should search for youpi.bad_extension files
#
server {
    listen 8080;
    host 127.0.0.1;
    server_name localhost;
    
    # Maximum client body size (1MB)
    client_max_body_size 1M;
    
    # Root directory
    root ./www_42tester;
    
    # Default index file
    index 42.html;
    
    # Root location
	# / must answer to GET request ONLY
    location / {
        allowed_methods GET;
        root ./www_42tester/html;
		autoindex on;
    }

	# Any file with .bla as extension must answer to
	# POST request by calling the cgi_test executable
	#
	# /post_body must answer anything to POST request with
	# a maxBody of 100
	location /post_body {
        allowed_methods GET POST;
		alias ./www_42tester/html;
		upload_path ./www_42tester/uploads;
		cgi_pass .bla ./www_42tester/cgi-bin/cgi-tester;
		autoindex on;
        client_max_body_size 100;
	}

	# /directory/ must answer to GET request and the root of it
	# would be the repository YoupiBanane and if no file are requested,
	# it should search for youpi.bad_extension files
	location /directory/ {
        allowed_methods GET POST;
		alias ./www_42tester/html/YoupiBanane;
		upload_path ./www_42tester/uploads;
		cgi_pass .bla ./www_42tester/cgi-bin/cgi-tester;
		index youpi.bad_extension;
	}
}
