#!/usr/bin/php-cgi
<?php
header("Content-Type: text/html");
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>CGI Test</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
            background-color: #f5f5f5;
        }
        .container {
            background: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #007bff;
            color: white;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>CGI Test - PHP</h1>
        <p>This page is generated by PHP-CGI</p>
        
        <h2>Server Information:</h2>
        <table>
            <tr>
                <th>Variable</th>
                <th>Value</th>
            </tr>
            <tr>
                <td>SERVER_SOFTWARE</td>
                <td><?php echo $_SERVER['SERVER_SOFTWARE'] ?? 'N/A'; ?></td>
            </tr>
            <tr>
                <td>REQUEST_METHOD</td>
                <td><?php echo $_SERVER['REQUEST_METHOD'] ?? 'N/A'; ?></td>
            </tr>
            <tr>
                <td>QUERY_STRING</td>
                <td><?php echo $_SERVER['QUERY_STRING'] ?? 'N/A'; ?></td>
            </tr>
            <tr>
                <td>SCRIPT_NAME</td>
                <td><?php echo $_SERVER['SCRIPT_NAME'] ?? 'N/A'; ?></td>
            </tr>
            <tr>
                <td>Current Time</td>
                <td><?php echo date('Y-m-d H:i:s'); ?></td>
            </tr>
        </table>
        
        <p><a href="/">← Back to Home</a></p>
    </div>
</body>
</html>
