#!/bin/bash

SERVER_BINARY="../../bin/webserv"
SERVER_HOST=
SERVER_PORT=
SERVER_CONFIG_FILE="./resources/test_DELETE_requests/test.conf"

TEST_BASE_DIR="./resources"

CAT_REQUEST_BINARY="./bin/cat_request"

create_next_output_dir() {
	# Create empty array
	local dirs=()

	# Find all directories and sort then, add them to the array
	while IFS= read -r entry; do
		dirs+=("$entry")
	done < <(find . -maxdepth 1 -type d -name 'output_*' | sort -V)

	local last_dir="output_0"
	if [ ! ${#dirs[@]} -eq 0 ]; then
		# Get the last directory in sorted order
		last_dir="${dirs[-1]}"
	fi

	local num=0

	# Extract the number from the last directory
	if [[ "$last_dir" =~ output_([0-9]+)$ ]]; then
		num="${BASH_REMATCH[1]}"
	fi

	# Increment the number
	local next_num=$((10#$num + 1))

	# Create new directory with the incremented number
	new_dir="output_$next_num"
	mkdir "$new_dir"
	echo "$new_dir"
}

is_process_running() {
	if [ -z "$1" ]; then
		return 1 # process is definitely not running
	fi

	if kill -0 "$1" 2>/dev/null; then
		return 0 # set to success, yes, the process is running
	else
		return 1 # process is not running
	fi
}

TEST_OUTPUT_DIR=$(create_next_output_dir)

if [ ! -f $SERVER_BINARY ]; then
	echo "ERROR: $SERVER_BINARY not found!"
	exit 1
fi

# Requires 3 arguments: server_binary, server_config_file, test_output_dir
# Sets 3 global variables: SERVER_PID, SERVER_HOST, SERVER_PORT for later use
start_web_server() {
	local server_binary="$1"
	local server_config_file="$2"
	local test_output_dir="$3"

	export server_binary
	export server_config_file
	export test_output_dir

	echo "Starting the server..."
	(
		$server_binary "$server_config_file" >"${test_output_dir}/server_log" 2>&1
	) &
	SERVER_PID=$!

	sleep 0.25

	# get running server host and port from the logs for later use
	local server_addr=$(cat "$test_output_dir/server_log" | head -1 | awk '{print $4}')
	SERVER_HOST=${server_addr%:*}
	SERVER_PORT=${server_addr##*:}

	if is_process_running "$SERVER_PID"; then
		echo "OK: Server is now running (pid = $SERVER_PID) and listening on $SERVER_HOST:$SERVER_PORT"
		return 0
	else
		echo "ERROR: failed to start server, see ${test_output_dir}/server_log for details"
		return 1
	fi
}

stop_web_server() {
	local server_pid="$1"
	local test_output_dir="$2"

	if is_process_running "$server_pid"; then
		echo "STOPPING the server!"
		kill -SIGINT "$server_pid"
		return 0
	else
		echo "ERROR: server must have died, see ${test_output_dir}/server_log for details"
		return 1
	fi
}

extract_header_line() {
	local file="$1"
	local header_line=$(cat $file | grep -v "#" | head -1 | sed 's/\\r\\n$//')
	echo "$header_line"
}

send_req_files_log_responses_compare() {
	local cat_request="$1"
	local base_path="$2"
	local base_len="${#base_path}"
	local log_dir_base_path="$3"

	#echo "Base dir is $base_path"

	while read -r dir; do
		# Remove the base path prefix
		rel_dir="${dir#$base_path/}"
		log_dir="$log_dir_base_path/$rel_dir"

		txt_files=("$dir"/*.req)
		if [ -e "${txt_files[0]}" ]; then
			#echo "  RELATIVE dir is $rel_dir"
			#echo "  Sending requests from $rel_dir/"

			mkdir -p "$log_dir"

			# List files in this directory
			while read -r request_file_with_path; do
				request_filename="$(basename "$request_file_with_path")"
				response_filename="${request_filename%.*}.res"
				local request_header=$(extract_header_line "$request_file_with_path")
				echo "    Sending request : $request_header  from $request_filename"
				echo "                      "

				#echo "  Stored response to: $log_dir/$response_filename"
				#touch "$log_dir/$response_filename"
				$CAT_REQUEST_BINARY "$request_file_with_path" | netcat -N "$SERVER_HOST" "$SERVER_PORT" >"$log_dir/$response_filename"
			done < <(find "$dir" -maxdepth 1 -type f -name "*.req")
		fi
	done < <(find "$base_path" -type d)
}

TEST_GROUPS=()
while IFS= read -r entry; do
	TEST_GROUPS+=("$entry")
done < <(find $TEST_BASE_DIR -maxdepth 1 -type d -name 'test_*_requests' | sort -V)

for test_group in "${TEST_GROUPS[@]}"; do
	www_data_archive="$test_group/archived_www.tar.gz"

	if [ ! -f "$www_data_archive" ]; then
		echo "ERROR: could not find file $www_data_archive"
		break
	fi

	www_data_permissions_file="$test_group/permissions_data"

	if [ ! -f "$www_data_permissions_file" ]; then
		echo "ERROR: could not find file $www_data_permissions_file"
		break
	fi

	www_data_dir="$test_group/www"

	echo
	echo "Entering $test_group"
	echo

	if [ -d "$www_data_dir" ]; then
		./set_permissions.sh "$www_data_dir" 744
		rm -r "$www_data_dir"
	fi

	tar -xzf "$www_data_archive" -C "$test_group"
	if [ ! -d "$www_data_dir" ]; then
		echo "ERROR: could not find $www_data_dir after extracting from archive!"
		break
	fi

	./set_permissions.sh "$www_data_dir"
	echo "Test data ready in $www_data_dir"

	if ! start_web_server "$SERVER_BINARY" "$test_group/test.conf" "$TEST_OUTPUT_DIR"; then
		echo "Halting tests..."
		exit 1
	fi

	echo
	echo "Running tests from $test_group"
	echo

	requests_dir="$test_group/requests"
	send_req_files_log_responses_compare "$CAT_REQUEST_BINARY" "$requests_dir" "${TEST_OUTPUT_DIR}/responses"

	if ! stop_web_server "$SERVER_PID" "$TEST_OUTPUT_DIR"; then
		echo "ERROR: stop_web_server resulted in error!"
		exit 1
	fi
done
